packages:
  - "apps/sdkwork-account-common"
  - "apps/sdkwork-account-common/packages/*"
  - "apps/sdkwork-account-pc"
  - "apps/sdkwork-account-pc/packages/*"
  - "sdks/*"
  - "sdks/sdkwork-account-app-sdk/sdkwork-account-app-sdk-typescript/generated/server-openapi"
  - "sdks/sdkwork-account-backend-sdk/sdkwork-account-backend-sdk-typescript/generated/server-openapi"
  - "../sdkwork-appbase/packages/common/foundation/sdkwork-runtime-bootstrap"
  - "../sdkwork-appbase/packages/pc-react/foundation/sdkwork-appbase-pc-react"
  - "../sdkwork-appbase/packages/pc-react/foundation/sdkwork-i18n-pc-react"
  - "../sdkwork-ui/sdkwork-ui-pc-react"
  - "../sdkwork-utils/packages/sdkwork-utils-typescript"
  - "../sdkwork-sdk-commons/sdkwork-sdk-common-typescript"
  - "../sdkwork-order/apps/sdkwork-order-common/packages/*"
  - "../sdkwork-order/sdks/sdkwork-order-app-sdk/sdkwork-order-app-sdk-typescript/generated/server-openapi"

catalog:
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^6.0.1
  react: ^19.2.4
  react-dom: ^19.2.4
  react-router: ">=6.0.0 <8.0.0"
  react-router-dom: ">=6.0.0 <8.0.0"
  typescript: ~6.0.2
  vite: ^8.0.3
  vitest: ^4.1.2
