-- SDKWork account consolidated initialization baseline (sqlite)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/sqlite/0001_account_baseline.sql
-- sdkwork:migration
-- id: 0001_account_core
-- engine: sqlite
-- module: account
-- purpose: L3 account wallet, ledger, hold, journal, idempotency, outbox, billing
-- reversible: true
-- transactional: true

CREATE TABLE IF NOT EXISTS commerce_account (
    id INTEGER NOT NULL PRIMARY KEY,
    uuid TEXT NOT NULL UNIQUE,
    tenant_id INTEGER NOT NULL,
    organization_id INTEGER NOT NULL DEFAULT 0,
    owner_type TEXT NOT NULL DEFAULT 'USER',
    owner_id INTEGER NOT NULL,
    asset_code TEXT NOT NULL,
    currency_code TEXT NOT NULL DEFAULT '',
    account_purpose TEXT NOT NULL DEFAULT 'GENERAL',
    available_amount TEXT NOT NULL DEFAULT '0',
    frozen_amount TEXT NOT NULL DEFAULT '0',
    pending_amount TEXT NOT NULL DEFAULT '0',
    status INTEGER NOT NULL DEFAULT 1,
    version INTEGER NOT NULL DEFAULT 0,
    closed_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (
        tenant_id, organization_id, owner_type, owner_id,
        asset_code, currency_code, account_purpose
    )
);

CREATE INDEX IF NOT EXISTS idx_commerce_account_tenant_owner
    ON commerce_account (tenant_id, organization_id, owner_type, owner_id, asset_code);

CREATE TABLE IF NOT EXISTS commerce_account_journal (
    id INTEGER NOT NULL PRIMARY KEY,
    uuid TEXT NOT NULL UNIQUE,
    tenant_id INTEGER NOT NULL,
    business_type TEXT NOT NULL,
    business_no TEXT NOT NULL,
    request_no TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    trace_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE (tenant_id, idempotency_key),
    UNIQUE (tenant_id, business_no)
);

CREATE TABLE IF NOT EXISTS commerce_account_journal_line (
    id INTEGER NOT NULL PRIMARY KEY,
    journal_id INTEGER NOT NULL,
    account_id INTEGER NOT NULL,
    direction TEXT NOT NULL,
    amount TEXT NOT NULL,
    ledger_id INTEGER NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_commerce_account_journal_line_journal
    ON commerce_account_journal_line (journal_id);

CREATE TABLE IF NOT EXISTS commerce_account_ledger (
    id INTEGER NOT NULL PRIMARY KEY,
    uuid TEXT NOT NULL UNIQUE,
    tenant_id INTEGER NOT NULL,
    organization_id INTEGER NOT NULL DEFAULT 0,
    account_id INTEGER NOT NULL,
    journal_id INTEGER,
    owner_type TEXT NOT NULL,
    owner_id INTEGER NOT NULL,
    asset_code TEXT NOT NULL,
    currency_code TEXT NOT NULL DEFAULT '',
    ledger_type TEXT NOT NULL DEFAULT 'AVAILABLE',
    entry_type TEXT NOT NULL,
    direction TEXT NOT NULL,
    amount TEXT NOT NULL,
    balance_before TEXT NOT NULL,
    balance_after TEXT NOT NULL,
    business_type TEXT NOT NULL,
    business_no TEXT NOT NULL,
    request_no TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    source_type TEXT,
    source_id INTEGER,
    hold_id INTEGER,
    transfer_id INTEGER,
    reversed_ledger_id INTEGER,
    remark TEXT,
    trace_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE (tenant_id, business_no),
    UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_commerce_account_ledger_account_created
    ON commerce_account_ledger (tenant_id, account_id, created_at);
CREATE INDEX IF NOT EXISTS idx_commerce_account_ledger_request_no
    ON commerce_account_ledger (tenant_id, request_no);

CREATE TABLE IF NOT EXISTS commerce_account_hold (
    id INTEGER NOT NULL PRIMARY KEY,
    uuid TEXT NOT NULL UNIQUE,
    tenant_id INTEGER NOT NULL,
    organization_id INTEGER NOT NULL DEFAULT 0,
    account_id INTEGER NOT NULL,
    owner_type TEXT NOT NULL,
    owner_id INTEGER NOT NULL,
    asset_code TEXT NOT NULL,
    amount TEXT NOT NULL,
    settled_amount TEXT NOT NULL DEFAULT '0',
    released_amount TEXT NOT NULL DEFAULT '0',
    status INTEGER NOT NULL DEFAULT 1,
    business_type TEXT NOT NULL,
    business_no TEXT NOT NULL,
    source_type TEXT NOT NULL,
    source_id INTEGER NOT NULL,
    idempotency_key TEXT NOT NULL,
    request_no TEXT NOT NULL,
    expires_at TEXT,
    settled_at TEXT,
    released_at TEXT,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_commerce_account_hold_account
    ON commerce_account_hold (tenant_id, account_id, status);

CREATE TABLE IF NOT EXISTS commerce_account_transfer (
    id INTEGER NOT NULL PRIMARY KEY,
    uuid TEXT NOT NULL UNIQUE,
    tenant_id INTEGER NOT NULL,
    organization_id INTEGER NOT NULL DEFAULT 0,
    from_account_id INTEGER NOT NULL,
    to_account_id INTEGER NOT NULL,
    asset_code TEXT NOT NULL,
    amount TEXT NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    business_type TEXT NOT NULL,
    business_no TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    request_no TEXT NOT NULL,
    journal_id INTEGER NOT NULL,
    trace_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE (tenant_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS commerce_points_lot (
    id INTEGER NOT NULL PRIMARY KEY,
    uuid TEXT NOT NULL UNIQUE,
    tenant_id INTEGER NOT NULL,
    account_id INTEGER NOT NULL,
    granted_amount INTEGER NOT NULL,
    remaining_amount INTEGER NOT NULL,
    source_type TEXT NOT NULL,
    source_id INTEGER NOT NULL,
    expires_at TEXT,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_commerce_points_lot_account_expires
    ON commerce_points_lot (tenant_id, account_id, expires_at);

CREATE TABLE IF NOT EXISTS commerce_idempotency_record (
    id INTEGER NOT NULL PRIMARY KEY,
    uuid TEXT NOT NULL UNIQUE,
    tenant_id INTEGER NOT NULL,
    scope TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    request_hash TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id INTEGER,
    status TEXT NOT NULL,
    response_snapshot TEXT,
    locked_until TEXT,
    expire_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (tenant_id, scope, idempotency_key)
);

CREATE TABLE IF NOT EXISTS commerce_outbox_event (
    id INTEGER NOT NULL PRIMARY KEY,
    uuid TEXT NOT NULL UNIQUE,
    tenant_id INTEGER NOT NULL,
    aggregate_type TEXT NOT NULL,
    aggregate_id INTEGER NOT NULL,
    event_type TEXT NOT NULL,
    event_version INTEGER NOT NULL,
    event_key TEXT NOT NULL UNIQUE,
    payload TEXT NOT NULL,
    payload_hash TEXT NOT NULL,
    status TEXT NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TEXT,
    published_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_commerce_outbox_event_status_retry
    ON commerce_outbox_event (status, next_retry_at);

CREATE TABLE IF NOT EXISTS commerce_billing_history (
    id INTEGER NOT NULL PRIMARY KEY,
    uuid TEXT NOT NULL UNIQUE,
    tenant_id INTEGER NOT NULL,
    organization_id INTEGER NOT NULL DEFAULT 0,
    owner_type TEXT NOT NULL DEFAULT 'USER',
    owner_id INTEGER NOT NULL,
    history_no TEXT NOT NULL,
    history_type TEXT NOT NULL,
    direction TEXT NOT NULL,
    asset_code TEXT NOT NULL,
    amount TEXT NOT NULL,
    currency_code TEXT NOT NULL DEFAULT '',
    points_delta INTEGER NOT NULL DEFAULT 0,
    status INTEGER NOT NULL,
    title TEXT NOT NULL,
    reference_no TEXT,
    source_type TEXT NOT NULL,
    source_id INTEGER NOT NULL,
    related_order_id INTEGER,
    related_order_no TEXT,
    payment_method TEXT,
    occurred_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    UNIQUE (tenant_id, history_no)
);

CREATE INDEX IF NOT EXISTS idx_commerce_billing_history_owner_occurred
    ON commerce_billing_history (tenant_id, owner_id, occurred_at);
