//! Generated gateway bootstrap for sdkwork-account.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;
use sdkwork_account_service_host::AccountServiceHost;
use std::sync::Arc;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub async fn assemble_application_router(host: Arc<AccountServiceHost>) -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_account_app_api::gateway_mount(host.clone()).await);
    router = router.merge(sdkwork_routes_account_backend_api::gateway_mount(host).await);
    ApplicationAssembly { router }
}
