[package]
name = "sdkwork-api-account-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-account application HTTP plane."

[lib]
name = "sdkwork_api_account_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork_account_service_host.workspace = true
sdkwork-routes-account-app-api = { path = "../sdkwork-routes-account-app-api" }
sdkwork-routes-account-backend-api = { path = "../sdkwork-routes-account-backend-api" }
