use sdkwork_contract_service::CommerceServiceContract;

pub fn account_service_contract() -> CommerceServiceContract {
    CommerceServiceContract::new(
        "account",
        "commerce.account",
        vec![
            "wallet.adjustments.create",
            "wallet.adjustments.cash.create",
            "wallet.adjustments.points.create",
            "wallet.adjustments.tokens.create",
            "wallet.holds.create",
            "wallet.holds.settle",
            "wallet.holds.release",
            "wallet.transfers.create",
        ],
        vec![
            "accounts.current.summary.retrieve",
            "wallet.overview.retrieve",
            "wallet.accounts.list",
            "wallet.accounts.cash.retrieve",
            "wallet.accounts.points.retrieve",
            "wallet.accounts.tokens.retrieve",
            "wallet.ledgerEntries.list",
            "wallet.ledgerEntries.cash.list",
            "wallet.ledgerEntries.points.list",
            "wallet.ledgerEntries.retrieve",
            "wallet.points.lots.list",
            "wallet.holds.list",
            "wallet.holds.retrieve",
            "wallet.tokens.retrieve",
            "billing.history.list",
        ],
        vec![
            crate::ports::ACCOUNT_REPOSITORY_PORT,
            crate::ports::ACCOUNT_WALLET_READ_PORT,
            crate::ports::ACCOUNT_LEDGER_WRITE_PORT,
            crate::ports::BILLING_HISTORY_READ_PORT,
            crate::ports::IDEMPOTENCY_REPOSITORY_PORT,
        ],
        true,
    )
}
