-- SDKWork account consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_account_baseline.sql
-- sdkwork:migration
-- id: 0001_account_core
-- engine: postgres
-- module: account
-- purpose: L3 account wallet, ledger, hold, journal, idempotency, outbox, billing
-- reversible: true
-- transactional: true

CREATE TABLE IF NOT EXISTS commerce_account (
    id BIGINT NOT NULL,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    owner_type VARCHAR(32) NOT NULL DEFAULT 'USER',
    owner_id BIGINT NOT NULL,
    asset_code VARCHAR(32) NOT NULL,
    currency_code VARCHAR(10) NOT NULL DEFAULT '',
    account_purpose VARCHAR(32) NOT NULL DEFAULT 'GENERAL',
    available_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    frozen_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    pending_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    version BIGINT NOT NULL DEFAULT 0,
    closed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_commerce_account PRIMARY KEY (id),
    CONSTRAINT uk_commerce_account_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_account_owner_asset UNIQUE (
        tenant_id, organization_id, owner_type, owner_id,
        asset_code, currency_code, account_purpose
    ),
    CONSTRAINT chk_commerce_account_amounts_non_negative CHECK (
        available_amount >= 0 AND frozen_amount >= 0 AND pending_amount >= 0
    )
);

CREATE INDEX IF NOT EXISTS idx_commerce_account_tenant_owner
    ON commerce_account (tenant_id, organization_id, owner_type, owner_id, asset_code);

CREATE TABLE IF NOT EXISTS commerce_account_journal (
    id BIGINT NOT NULL,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    business_type VARCHAR(64) NOT NULL,
    business_no VARCHAR(128) NOT NULL,
    request_no VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    trace_id VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_commerce_account_journal PRIMARY KEY (id),
    CONSTRAINT uk_commerce_account_journal_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_account_journal_idempotency UNIQUE (tenant_id, idempotency_key),
    CONSTRAINT uk_commerce_account_journal_business_no UNIQUE (tenant_id, business_no)
);

CREATE TABLE IF NOT EXISTS commerce_account_journal_line (
    id BIGINT NOT NULL,
    journal_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    direction VARCHAR(16) NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    ledger_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_commerce_account_journal_line PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_commerce_account_journal_line_journal
    ON commerce_account_journal_line (journal_id);

CREATE TABLE IF NOT EXISTS commerce_account_ledger (
    id BIGINT NOT NULL,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    account_id BIGINT NOT NULL,
    journal_id BIGINT,
    owner_type VARCHAR(32) NOT NULL,
    owner_id BIGINT NOT NULL,
    asset_code VARCHAR(32) NOT NULL,
    currency_code VARCHAR(10) NOT NULL DEFAULT '',
    ledger_type VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE',
    entry_type VARCHAR(32) NOT NULL,
    direction VARCHAR(16) NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    balance_before NUMERIC(18, 2) NOT NULL,
    balance_after NUMERIC(18, 2) NOT NULL,
    business_type VARCHAR(64) NOT NULL,
    business_no VARCHAR(128) NOT NULL,
    request_no VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    source_type VARCHAR(64),
    source_id BIGINT,
    hold_id BIGINT,
    transfer_id BIGINT,
    reversed_ledger_id BIGINT,
    remark VARCHAR(512),
    trace_id VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_commerce_account_ledger PRIMARY KEY (id),
    CONSTRAINT uk_commerce_account_ledger_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_account_ledger_business_no UNIQUE (tenant_id, business_no),
    CONSTRAINT uk_commerce_account_ledger_idempotency UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_commerce_account_ledger_account_created
    ON commerce_account_ledger (tenant_id, account_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_commerce_account_ledger_request_no
    ON commerce_account_ledger (tenant_id, request_no);

CREATE TABLE IF NOT EXISTS commerce_account_hold (
    id BIGINT NOT NULL,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    account_id BIGINT NOT NULL,
    owner_type VARCHAR(32) NOT NULL,
    owner_id BIGINT NOT NULL,
    asset_code VARCHAR(32) NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    settled_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    released_amount NUMERIC(18, 2) NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT 1,
    business_type VARCHAR(64) NOT NULL,
    business_no VARCHAR(128) NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    source_id BIGINT NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_no VARCHAR(128) NOT NULL,
    expires_at TIMESTAMPTZ,
    settled_at TIMESTAMPTZ,
    released_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_commerce_account_hold PRIMARY KEY (id),
    CONSTRAINT uk_commerce_account_hold_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_account_hold_idempotency UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_commerce_account_hold_account
    ON commerce_account_hold (tenant_id, account_id, status);

CREATE TABLE IF NOT EXISTS commerce_account_transfer (
    id BIGINT NOT NULL,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    from_account_id BIGINT NOT NULL,
    to_account_id BIGINT NOT NULL,
    asset_code VARCHAR(32) NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    business_type VARCHAR(64) NOT NULL,
    business_no VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_no VARCHAR(128) NOT NULL,
    journal_id BIGINT NOT NULL,
    trace_id VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_commerce_account_transfer PRIMARY KEY (id),
    CONSTRAINT uk_commerce_account_transfer_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_account_transfer_idempotency UNIQUE (tenant_id, idempotency_key)
);

CREATE TABLE IF NOT EXISTS commerce_points_lot (
    id BIGINT NOT NULL,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    granted_amount BIGINT NOT NULL,
    remaining_amount BIGINT NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    source_id BIGINT NOT NULL,
    expires_at TIMESTAMPTZ,
    status INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_commerce_points_lot PRIMARY KEY (id),
    CONSTRAINT uk_commerce_points_lot_uuid UNIQUE (uuid)
);

CREATE INDEX IF NOT EXISTS idx_commerce_points_lot_account_expires
    ON commerce_points_lot (tenant_id, account_id, expires_at);

CREATE TABLE IF NOT EXISTS commerce_idempotency_record (
    id BIGINT NOT NULL,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    scope VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    request_hash VARCHAR(128) NOT NULL,
    target_type VARCHAR(64) NOT NULL,
    target_id BIGINT,
    status VARCHAR(32) NOT NULL,
    response_snapshot JSONB,
    locked_until TIMESTAMPTZ,
    expire_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_commerce_idempotency_record PRIMARY KEY (id),
    CONSTRAINT uk_commerce_idempotency_record_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_idempotency_record_key UNIQUE (tenant_id, scope, idempotency_key)
);

CREATE TABLE IF NOT EXISTS commerce_outbox_event (
    id BIGINT NOT NULL,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    event_version INTEGER NOT NULL,
    event_key VARCHAR(200) NOT NULL,
    payload JSONB NOT NULL,
    payload_hash VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_commerce_outbox_event PRIMARY KEY (id),
    CONSTRAINT uk_commerce_outbox_event_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_outbox_event_key UNIQUE (event_key)
);

CREATE INDEX IF NOT EXISTS idx_commerce_outbox_event_status_retry
    ON commerce_outbox_event (status, next_retry_at);

CREATE TABLE IF NOT EXISTS commerce_billing_history (
    id BIGINT NOT NULL,
    uuid VARCHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    organization_id BIGINT NOT NULL DEFAULT 0,
    owner_type VARCHAR(32) NOT NULL DEFAULT 'USER',
    owner_id BIGINT NOT NULL,
    history_no VARCHAR(128) NOT NULL,
    history_type VARCHAR(64) NOT NULL,
    direction VARCHAR(16) NOT NULL,
    asset_code VARCHAR(32) NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    currency_code VARCHAR(10) NOT NULL DEFAULT '',
    points_delta BIGINT NOT NULL DEFAULT 0,
    status INTEGER NOT NULL,
    title VARCHAR(256) NOT NULL,
    reference_no VARCHAR(128),
    source_type VARCHAR(64) NOT NULL,
    source_id BIGINT NOT NULL,
    related_order_id BIGINT,
    related_order_no VARCHAR(128),
    payment_method VARCHAR(64),
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_commerce_billing_history PRIMARY KEY (id),
    CONSTRAINT uk_commerce_billing_history_uuid UNIQUE (uuid),
    CONSTRAINT uk_commerce_billing_history_no UNIQUE (tenant_id, history_no)
);

CREATE INDEX IF NOT EXISTS idx_commerce_billing_history_owner_occurred
    ON commerce_billing_history (tenant_id, owner_id, occurred_at DESC);
